apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-21T06:39:16Z"
  labels:
    x: dhprc-1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:x: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3456,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:x: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-01-21T06:39:16Z"
  name: dhpsvc2
  namespace: default
  resourceVersion: "31660"
  uid: b0637134-1abd-4f6b-ade0-d35f42d83d00
spec:
  clusterIP: 10.111.128.158
  clusterIPs:
  - 10.111.128.158
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32687
    port: 3456
    protocol: TCP
    targetPort: 8080
  selector:
    x: dhppod-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
