apiVersion: v1
kind: Service  #API resource type
metadata:
  creationTimestamp: null
  labels: #label of service
    app: dhpsvc1
  name: dhpsvc1 #name for the Service
spec:
  ports:
  - name: 4567-80
    port: 4567  #PORT of on the service
    protocol: TCP
    targetPort: 80 # PORT of the Pod application
  selector: # finder for the serch program Label of the POD should be put here.
    x: helloadhp
  type: NodePort  #Service type
status:
  loadBalancer: {} #inbuilt LBR capability
