apiVersion: v1 # this is my apiversion fo k8s
kind: Pod
metadata:
 name: dhp-pod-1 # make sure unique pod name
 labels:
   x: helloadhp  # label of POD -- so that service can find it
spec:
 containers:
 - image: nginx
   name: dhavaluc1
   ports:
   - containerPort: 80
