apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dhavalpod2
  name: dhavalpod2
spec:
  containers:
  - image: nginx
    name: dhavalpod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
